type: http
name: List loan applications
url: '{{baseUrl}}/applications?status=withdrawn&productType=home_equity&limit=25&offset=0'
method: GET
headers:
  - key: Accept
    value: application/json
queryParams:
  - key: status
    value: withdrawn
    description: Filter by application status
  - key: productType
    value: home_equity
    description: Filter by loan product type
  - key: limit
    value: '25'
  - key: offset
    value: '0'
examples:
  - response:
      statusCode: 200
      statusText: OK
      body:
        type: json
        content: |-
          {
            "data": [
              {
                "id": "string",
                "applicantId": "string",
                "productType": "string",
                "requestedAmount": 8362.499567026012,
                "termMonths": 9990,
                "status": "submitted",
                "createdAt": "1992-04-22T03:03:45.156Z",
                "updatedAt": "2001-10-01T14:16:17.681Z",
                "underwritingResult": {
                  "applicationId": "string",
                  "status": "failed",
                  "decision": "denied",
                  "riskScore": 22,
                  "evaluatedAt": "1977-03-27T08:25:55.013Z"
                }
              },
              {
                "id": "string",
                "applicantId": "string",
                "productType": "string",
                "requestedAmount": 3655.497383381332,
                "termMonths": 2953,
                "status": "approved",
                "createdAt": "1989-09-17T08:15:09.622Z",
                "updatedAt": "1997-06-23T10:46:56.024Z",
                "underwritingResult": {
                  "applicationId": "string",
                  "status": "completed",
                  "decision": "denied",
                  "riskScore": 44,
                  "evaluatedAt": "2006-05-05T10:03:26.702Z"
                }
              }
            ],
            "total": 5947,
            "limit": 4161,
            "offset": 1640
          }
      headers:
        - key: Content-Type
          value: application/json
    name: List of applications
