type: http
name: List loan applications
url: '{{baseUrl}}/applications?status=denied&productType=business_loan&limit=25&offset=0'
method: GET
headers:
  - key: Accept
    value: application/json
queryParams:
  - key: status
    value: denied
    description: Filter by application status
  - key: productType
    value: business_loan
    description: Filter by loan product type
  - key: limit
    value: '25'
  - key: offset
    value: '0'
examples:
  - response:
      statusCode: 200
      statusText: OK
      body:
        type: json
        content: |-
          {
            "data": [
              {
                "id": "string",
                "applicantId": "string",
                "productType": "string",
                "requestedAmount": 9299.059111099288,
                "termMonths": 280,
                "status": "denied",
                "createdAt": "1974-09-23T06:48:01.492Z",
                "updatedAt": "1976-11-01T11:46:10.655Z",
                "underwritingResult": {
                  "applicationId": "string",
                  "status": "pending",
                  "decision": "approved",
                  "riskScore": 7,
                  "evaluatedAt": "1976-01-29T11:21:53.832Z"
                }
              },
              {
                "id": "string",
                "applicantId": "string",
                "productType": "string",
                "requestedAmount": 8352.1314890205,
                "termMonths": 4302,
                "status": "withdrawn",
                "createdAt": "1992-08-03T02:55:59.679Z",
                "updatedAt": "1982-06-02T15:32:30.153Z",
                "underwritingResult": {
                  "applicationId": "string",
                  "status": "pending",
                  "decision": "denied",
                  "riskScore": 80,
                  "evaluatedAt": "2022-05-17T12:55:03.634Z"
                }
              }
            ],
            "total": 2038,
            "limit": 3087,
            "offset": 7337
          }
      headers:
        - key: Content-Type
          value: application/json
    name: List of applications
