type: http
name: List application documents
url: '{{baseUrl}}/applications/:applicationId/documents'
method: GET
headers:
  - key: Accept
    value: application/json
pathVariables:
  - key: applicationId
    value: string
examples:
  - response:
      statusCode: 200
      statusText: OK
      body:
        type: json
        content: |-
          [
            {
              "id": "string",
              "applicationId": "string",
              "documentType": "string",
              "fileName": "string",
              "uploadedAt": "2009-03-23T17:08:41.973Z",
              "verificationStatus": "verified"
            },
            {
              "id": "string",
              "applicationId": "string",
              "documentType": "string",
              "fileName": "string",
              "uploadedAt": "1983-02-05T02:55:20.430Z",
              "verificationStatus": "rejected"
            }
          ]
      headers:
        - key: Content-Type
          value: application/json
    name: List of documents
