type: http
name: Get application details
url: '{{baseUrl}}/applications/:applicationId'
method: GET
headers:
  - key: Accept
    value: application/json
pathVariables:
  - key: applicationId
    value: string
examples:
  - response:
      statusCode: 200
      statusText: OK
      body:
        type: json
        content: |-
          {
            "id": "string",
            "applicantId": "string",
            "productType": "string",
            "requestedAmount": 5571.9554287066985,
            "termMonths": 1287,
            "status": "withdrawn",
            "createdAt": "1982-05-12T16:06:30.906Z",
            "updatedAt": "1995-03-16T07:13:51.410Z",
            "underwritingResult": {
              "applicationId": "string",
              "status": "in_progress",
              "decision": "approved",
              "riskScore": 63,
              "evaluatedAt": "1982-04-24T05:18:19.010Z"
            }
          }
      headers:
        - key: Content-Type
          value: application/json
    name: Application details
  - response:
      statusCode: 404
      statusText: Not Found
      body:
        type: json
        content: |-
          {
            "code": "string",
            "message": "string",
            "details": {}
          }
      headers:
        - key: Content-Type
          value: application/json
    name: Application not found
